version: "3"
services:

  collabnet:
    build: ./
    image: dcagatay/subversion-edge:latest
    # environment:
      # PUID: "4444"
      # PGID: "5555"
    # volumes:
      # - ./data:/opt/csvn/data
    ports:
      - 3343:3343
      - 18080:18080
    restart: unless-stopped
